### PR TITLE
Removes the no multiarch build flag

### LINKED ISSUE #87: RBGL errors: single architecture?
I am getting errors in a package that I think can be traced to a problem I have not seen in the past with RBGL.

When my `appeyor.yml` file has `travis-tool.sh install_bioc RBGL`  it seems to run successfully as I eventually see (https://ci.appveyor.com/project/rdiaz02/OncoSimul/build/job/0wwqwkbq5ldw0qai)  (this is for a x64 build; similar but referring to i386 in the i386 build)

```
installing to c:/RLibrary/RBGL/libs/x64
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (RBGL
```

But I see the message 
```
Warning: this package has a non-empty 'configure.win' file,
so building only the main architecture
```

And then, further down below, when another package (`nem` in this case) that depends on RBGL has to be installed I see

```
*** arch - i386
Error: package or namespace load failed for 'nem' in library.dynam(lib, package, package.lib):
 DLL 'RBGL' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'c:/RLibrary/nem'RBGL
```

If I do not directly try to install RBGL and leave it for the dependencies to be resolved, the same thing happens (https://ci.appveyor.com/project/rdiaz02/oncosimul/build/1.0.372/job/5837y47575gax7mi) .

It seems I would need to use the proper magical combination of  `--merge-multiarch` and/or `--force-multiarch` (http://r.789695.n4.nabble.com/R-CMD-check-force-multiarch-does-not-install-all-the-archs-for-testing-td3629129.html) but I have not been able to get it to work, as appveyor seems to have the `INSTALL_opts="--no-multiarch"` harcoded.

Any possible workarounds?

### PR DESCRIPTION
**Pull request by nfultz**
Removes the no multiarch flag - this has been running on DeclareDesign appveyor builds for about two weeks just fine.

Closes #87

### CODE REVIEW

**Comment by asardaes** [comment]
If this is merged, the README should be updated

**Comment by krlmlr** [comment]
Thanks!

**Comment by krlmlr** [comment]
This seems to cause trouble with *rJava* (https://github.com/krlmlr/r-appveyor/issues/85#issuecomment-371790145), CC @MansMeg. Would you like to add a configuration option?

**Comment by MansMeg** [comment]
@krlmlr  Yes. What do you mean with a configuration option here?

**Comment by krlmlr** [comment]
Thanks. I think we could use the value of an environment variable for `INSTALL_opts`, and document it in `README.md`.

**Pull request merged**
