### PR TITLE
Provide more advice re: env vars

### PR DESCRIPTION
**Pull request by jennybc**
Motivated by discussion in https://github.com/r-lib/usethis/issues/640

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks!

**Comment by gaborcsardi** [comment]
pkgbuild does not have compiled code, so no standalone mode is needed there, but another one that fails to update often is rlang.

**Comment by jennybc** [comment]
Hmm, OK. I just copied that wording verbatim from the remotes README.

**Comment by jennybc** [comment]
Shall I make another PR and swap rlang for pkgbuild? Or should @krlmlr just make it so?

**Comment by krlmlr** [comment]
Fixed already, thanks!

**Pull request merged**
