### PR TITLE
Explicitly check the value of USE_RTOOLS.

### LINKED ISSUE #128: Explicitly setting USE_RTOOLS to false causes Rtools to be installed
## Observed behavior

I had set `USE_RTOOLS: true` so that I could build the latest versions of CRAN packages even when a binary version is not available. However, I recently decided that the added build time wasn't worth getting the latest package versions (compiling stringi was approximately doubling the build time). To make it easy to remember how to turn this back on in the future, I explicitly set the default of `USE_RTOOLS: false`. Unexpectedly, this caused Rtools to be installed.

## Expected behavior

I expected setting `USE_RTOOLS: false` to behave the same as the default when no `src/` directory is present.

## Examples

* `USE_RTOOLS: false`
    * [log](https://ci.appveyor.com/project/jdblischak/debugappveyor/builds/19650777#L42)
    * [yml](https://github.com/jdblischak/debugAppveyor/blob/1069beb471c3864e5378ba7ee8bb1b9b24370b85/appveyor.yml#L21)
* Not setting `USE_RTOOLS`
    * [log](https://ci.appveyor.com/project/jdblischak/debugappveyor/builds/19651159#L42)
    * [yml](https://github.com/jdblischak/debugAppveyor/blob/59519f24855bc39466043342d43f9012586c7e12/appveyor.yml)

### PR DESCRIPTION
**Pull request by jdblischak**
Close #128.

cc: @krlmlr @LiNk-NY

I tested the proposed behavior using the following function:

```powershell
Function Test_RTOOLS
{
  if ($env:USE_RTOOLS -eq "true") {
    Write-Host "RTOOLS will be installed"
  }
  Else {
    Write-Host "RTOOLS will NOT be installed"
  }
}
```

And it appears to work correctly:

```powershell
PS C:\Users\john> $env:USE_RTOOLS = "true"
PS C:\Users\john> Test_RTOOLS
RTOOLS will be installed

PS C:\Users\john> $env:USE_RTOOLS = "false"
PS C:\Users\john> Test_RTOOLS
RTOOLS will NOT be installed

PS C:\Users\john> $env:USE_RTOOLS = "bananas"
PS C:\Users\john> Test_RTOOLS
RTOOLS will NOT be installed

PS C:\Users\john> $env:USE_RTOOLS = ""
PS C:\Users\john> Test_RTOOLS
RTOOLS will NOT be installed
```

### CODE REVIEW

**Comment by LiNk-NY** [comment]
Hi John, thanks for testing this !

I wonder if this is robust to inputs like `TRUE` and `True`?
These are variations of what could be found in the `appveyor.yml` file (esp. for `True`).

Regards,
Marcel

**Comment by jdblischak** [comment]
> I wonder if this is robust to inputs like TRUE and True?
> These are variations of what could be found in the appveyor.yml file (esp. for True).

@LiNk-NY It's not. But the instructions in the README are quite explicit:

> Set `USE_RTOOLS: true` if Rtools needs to be installed

Also note that the environment variable `NOT_CRAN` is just as strict. `testthat::skip_on_cran()` requires it be be set to `"true"`.

https://github.com/r-lib/testthat/blob/8216ebe2d84028d1a7a315c5c17c15f93cad3d65/R/skip.R#L118

**Comment by jdblischak** [comment]
One job failed because of an [error trying to compile rlang](https://ci.appveyor.com/project/krlmlr/r-appveyor/builds/20626924/job/awo6pkb26m1vlhv3#L722).

**Comment by jdblischak** [comment]
I amended the commit to re-trigger the CI builds.

**Comment by jdblischak** [comment]
Same [rlang error](https://ci.appveyor.com/project/krlmlr/r-appveyor/builds/22235019/job/119by7gf9d5h9f0u#L674) as last time. Seems unrelated.

@krlmlr Could you please review this minor PR?

**Comment by krlmlr** [comment]
Thanks. I've looked for usages of `USE_RTOOLS` on GitHub, saw quite a few instances of `USE_RTOOLS: yes` (in addition to `USE_RTOOLS: true` which is the vast majority). The path of the least resistance here would be to support `USE_RTOOLS: yes` as well, we could also ping the owners of the affected repos. What do you think?

https://github.com/search?q=%22USE_RTOOLS%3A+yes%22&type=Code

**Comment by krlmlr** [comment]
Also, @msberends suggests in #133 to install Rtools also when `PKGTYPE` is not set to `win.binary`. I'm not sure about this (fixes one set of problems but opens up another one). Perhaps change both -- set the default for `PKGTYPE` to `win.binary` and install `RTOOLS` if it's set to anything else?

**Comment by jdblischak** [comment]
>  The path of the least resistance here would be to support `USE_RTOOLS: yes` as well

OK. I can add that.

> we could also ping the owners of the affected repos.

I can write a script to open an Issue on each of these repositories. Though the behavior won't change for them. The users that are going to be surprised are those that currently have RTOOLS installed when setting `USE_RTOOLS` to some string other than `yes` or `true` (unfortunately the GitHub search isn't case-sensitive so it's not trivial to find examples of, e.g. `USE_RTOOLS: TRUE` or `USE_RTOOLS: Yes`).

> set the default for `PKGTYPE` to `win.binary` and install `RTOOLS` if it's set to anything else?

I like this suggested behavior. Avoiding installing RTOOLS and source packages will be faster and is sufficient for most packages. If a user really needs to the very latest CRAN version of a package for the few days that it is not also available as a binary, then they can adjust the default settings.

However, how do I accomplish this technically? The setting `PKGTYPE` is defined in [travis-tool.sh](https://github.com/krlmlr/r-appveyor/blob/master/r-travis/scripts/travis-tool.sh#L11), but the decision to install `RTOOLS` is made prior to executing `travis-tool.sh`.

https://github.com/krlmlr/r-appveyor/blob/master/scripts/appveyor-tool.ps1#L161

**Comment by jdblischak** [comment]
I added support for `USE_RTOOLS: yes`. And since I'm not proficient in PowerShell, I confirmed that you can have multiple `-or` statements chained together by running the following:

```
if (('a' -eq 'b') -or ('b' -eq 'c') -or ('c' -eq 'c')) {Write-Host true}
```

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
